[features]
seeds = false
skip-lint = false
[programs.localnet]
donate3_contract_solana = "CL2oDTpfjkYhWxGeJUE35gbeuLmEPJ7Yw9Qs3qVZEt8q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/wgb/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
